name: workflow
on: push

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - runs: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit SHA: ${{ github.sha }}"
